image: gitpod/workspace-full

vscode:
  extensions:
    - ms-python.python

tasks:
  - name: Install dependencies
    before: |
      sudo apt update -y && sudo apt install -y mosquitto mosquitto-clients
      pyenv versions
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    command:
      mosquitto
