image: gitpod/workspace-full

vscode:
  extensions:
    - ms-python.python

tasks:
  - name: Install dependencies
    command: |
      pip install poetry
      poetry install --no-ansi --no-interaction
      exit

