image: gitpod/workspace-full

vscode:
  extensions:
    - ms-python.python

tasks:
  - name: Install dependencies
    init: |
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    command: |
      pip install -r requirements.txt
      pip install -r requirements-dev.txt

