[tool.poetry]
name = "stinger-ipc"
version = "0.0.1"
description = "Stinger IPC uses an interface description to generate server and client code for inter-process communications."
authors = ["Jacob Brunson <github@jacobbrunson.com>"]
license = "GPLv2"

[tool.poetry.dependencies]
python = "^3.8"
jacobs-jinja-too = "^0.0.6"
PyYAML = "^6.0"
yamlloader = "^1.1.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
jacobs-json-schema = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
