$id: "https://stingeripc.peargrove.com/stingeripc.schema.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
description: |
  This schema is used to validate StingerIPC stinger files.
type: object
parameters:
  stingeripc:
    type: string
    interface:
      type: object
      parameters:
        name:
          type: string
          version:
            type: string
      required:
        - name
        - version
  signals:
    type: object
    additionalProperties:
      type: object
      properties:
        payload:
          type: object
          properties:
            '$ref':
              type: string
  parameters:
    type: object
    additionalProperties:
      type: object
      properties:
        type:
          type: object
          properties:
            '$ref':
              type: string
required:
  - stingeripc
  - interface