$id: "https://stingeripc.peargrove.com/stingeripc.schema.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
description: |
  This schema is used to validate StingerIPC stinger files.
type: object

parameters:

  stingeripc:
    type: object
    properties:
      version:
        type: string
        const: "0.0.5"
    required:
      - version

  interface:
    type: object
    parameters:
      name:
        type: string
        version:
          type: string
    required:
      - name
      - version
  
  brokers:
    type: object
    additionalProperties:
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
        authentication:
          oneOf:
            - type: null
            - type: string
              const: "none"
            - type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      dependentRequired:
        host: ["port"]

  enums:
    type: object
    additionalProperties:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
        required: [name]

  signals:
    type: object
    additionalProperties:
      $ref: "#/$defs/signal"

  params:
    type: object
    additionalProperties:
      $ref: "#/$defs/param"

required:
  - stingeripc
  - interface

$defs:

  payload:
    type: array
    uniqueItems: true
    items:
      type: object
      required: ["type"]
      properties:
        description:
          type: string
      oneOf:
        - properties:
            type:
              type: string
              const: "float"
            initialValue:
              type: float
        - properties:
            type:
              type: string
              const: "string"
            initialValue:
              type: string
        - properties:
            type:
              type: string
              const: "integer"
            initialValue:
              type: integer
        - properties:
            type:
              type: string
              const: "boolean"
            initialValue:
              type: boolean
        - properties:
            type: 
              type: string
              const: "enum"
            enumName:
              type: string
            initialValue:
              type: string
          required: ["enumName"]
            
  signal:
    type: object
    properties:
      payload:
        $ref: "#/$defs/payload"

  param:
    type: object
    properties:
      payload:
        allOf:
          - $ref: "#/$defs/payload"
          - items:
              required: ["initialValue"]
    required:
      - payload